version: "3.9"

services:

  database:
    image: postgres:alpine3.18
    container_name: ft_transcendence_database
    env_file:
      - .env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - dbvol:/var/lib/postgresql/data
  
  backend:
    build: ./
    container_name: ft_transcendence_backend
    restart: always
    ports:
      - 3001:3001
      - 5555:5555
    depends_on:
      - database
    volumes:
      - ./backend/:/app
    environment:
      - IP_ADDRESS=${IP_ADDRESS}
      - POSTGRES_HOST=${POSTGRES_HOST}
    command: sh -c 'npm install && npx prisma db push && npm run start:dev'
  
  frontend:
    build: ./
    container_name: ft_transcendence_frontend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/app
    environment:
      - IP_ADDRESS=${IP_ADDRESS}
      - POSTGRES_HOST=${POSTGRES_HOST}
    command: sh -c 'npm install && npm run start'
      
volumes:
  dbvol: