version: "3.9"

services:

  # database:
  
  backend:
    build: ./backend/
    container_name: ft_transcendence_backend
    env_file:
      - .env
  
  frontend:
    build: ./frontend/
    container_name: ft_transcendence_frontend
    env_file:
      - .env