version: "3.9"

services:

  database:
    image: postgres:alpine3.18
    container_name: ft_transcendence_database
    env_file:
      - .env
    restart: always
    ports:
      - 3002:3002
    volumes:
      - dbvol:/var/lib/postgresql/data
  
  backend:
    build: ./backend/
    container_name: ft_transcendence_backend
    env_file:
      - .env
    depends_on:
      - database
  
  frontend:
    build: ./frontend/
    container_name: ft_transcendence_frontend
    env_file:
      - .env

volumes:
  dbvol: